version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: my-postgres-compose
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg_network
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: my-pgadmin-compose
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-myadminsecretpassword}
    volumes:
      - pgadmin_app_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - pg_network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_db_data:
    driver: local
  pgadmin_app_data:
    driver: local

networks:
  pg_network:
    driver: bridge
